### ISSUE TITLE
Functionality issues.

### ISSUE THREAD

**Issue by sumaiyamannan** [jrangelardila/moodle-format_btns#2]
hi,
The app has the below functional issues:

- The buttons are not in the order of the sections
- The active button is not highlighted but some other button is highlighted

![Screenshot from 2024-06-12 09-55-49](https://github.com/jrangelardila/moodle-format_btns/assets/43946803/3da903ee-f4df-4e93-a15e-9b1c121af885)

**Comment by jrangelardila** [comment]
Hello

Yes, indeed. It happened because I was ordering the sections by their id, and I had to do it by their section attribute.

The setting has already been raised.
