### ISSUE TITLE
Use of PHP super globals

### ISSUE THREAD

**Issue by sumaiyamannan** [jrangelardila/moodle-format_btns#3]
Hi,
The plugin uses superglobals  like $$_SERVER['REQUEST_URI'] and $_GET which are a matter of security concern.
You can instead use Moodle globals like $ME or $FULLME  or required_param() or optional_param() 

https://github.com/jrangelardila/moodle-format_btns/blob/master/classes/output/courseformat/content.php#L254

Regards,
Sumaiya

**Comment by danmarsden** [comment]
Thanks Sumaiya - I agree this is a blocker for plugins db approval - for more information on Moodle's security guidelines see:
https://moodledev.io/general/development/policies/security#summary-of-the-guidelines

**Comment by jrangelardila** [comment]
Realice el cambio a la función, teniendo en cuenta los comentarios aportados:

![image](https://github.com/jrangelardila/moodle-format_btns/assets/43287720/9e3e9506-e774-40c0-bd42-508db884c8d2)

The change has already gone up

**Comment by jrangelardila** [comment]
Make the change to the function, taking into account the comments provided:


![image](https://github.com/jrangelardila/moodle-format_btns/assets/43287720/cec2c71c-d453-4c0e-afd1-49df051fb95e)

**Comment by danmarsden** [comment]
Using param_raw misses the point. Please go back and read the security guidelines to understand what the purpose of doing this is.

**Comment by jrangelardila** [comment]
Dan, indeed, checking should be PARAM_INT, not PARAM_RAW

![image](https://github.com/jrangelardila/moodle-format_btns/assets/43287720/ef25fc79-b426-44b6-aa6f-bdb01789ffaa)
