### ISSUE TITLE
plugins db is not detailed enough

### ISSUE THREAD

**Issue by danmarsden** [jrangelardila/moodle-format_btns#4]
the description in your moodle.org plugins db entry is not detailed enough - you need to more clearly state the features that your plugin provides and potentially how it differs from the exisitng buttons format that you have based this on.

**Comment by jrangelardila** [comment]
Hello

Add one more paragraph, what happens is that the idea is to give more differences apart from the already existing ones for format_buttons, but I will do this over time, for now and what I feel is essential, is to have a similar complement in versions from moodle 4.2 upwards.
