### ISSUE TITLE
error Component was not valid: format_onetopic

### ISSUE THREAD

**Issue by labretagne** [jrangelardila/moodle-format_btns#7]
On Moodle 4.4.3 I installed the latest Release 1.7 of Btns Format but when displaying courses configured with this format, I got an error:
Component was not valid: format_onetopic

in the apache logs there is:
AH01071: Got error 'PHP message: Default exception handler: Erreur de programmation d\xc3\xa9tect\xc3\xa9e. Ceci doit \xc3\xaatre corrig\xc3\xa9 par un programmeur\xc2\xa0: Component was not valid: format_onetopic Debug: \nError code: codingerror\n* line 65 of /lib/classes/output/mustache_template_finder.php: coding_exception thrown\n* line 114 of /lib/classes/output/mustache_template_finder.php: call to core\\output\\mustache_template_finder::get_template_directories_for_component()\n* line 54 of /lib/classes/output/mustache_filesystem_loader.php: call to core\\output\\mustache_template_finder::get_template_filepath()\n* line 99 of /lib/mustache/src/Mustache/Loader/FilesystemLoader.php: call to core\\output\\mustache_filesystem_loader->getFileName()\n* line 82 of /lib/mustache/src/Mustache/Loader/FilesystemLoader.php: call to Mustache_Loader_FilesystemLoader->loadFile()\n* line 81 of /lib/classes/output/mustache_filesystem_loader.php: call to Mustache_Loader_FilesystemLoader->load()\n* line 692 of /lib/mustache/src/Mustache/Engine.php: call to core\\output\\mus...', referer: https:xxxxxxxxxxxxxxxxxxxxxxx

Cordialy

**Comment by jrangelardila** [comment]
The changed was made

**Comment by labretagne** [comment]
thank you for your quick and efficient intervention :)
